"use client"

/**
 * @description all application icons
 * @type {IconType}
 * @returns {React.JSX.Element}
 */
export { BiLogoTypescript as TypeScript } from "react-icons/bi"
export { CgRemote as RemoteDesktop } from "react-icons/cg"
export { FaArrowTurnUp as Up } from "react-icons/fa6"
export { FaGulp as Gulp } from "react-icons/fa6"
export { FaNodeJs as Node } from "react-icons/fa"
export { FaReact as React } from "react-icons/fa"
export { FaSass as Scss } from "react-icons/fa6"
export { IoEye as Eye } from "react-icons/io5"
export { IoIosArrowDown as Arrow } from "react-icons/io"
export { IoLogoCss3 as Css } from "react-icons/io"
export { IoLogoGithub as Github } from "react-icons/io5"
export { IoLogoHtml5 as Html } from "react-icons/io5"
export { IoMoon as Moon } from "react-icons/io5"
export { IoSunnySharp as Sun } from "react-icons/io5"
export { RiNextjsFill as Next } from "react-icons/ri"
export { RiTailwindCssFill as Tailwind } from "react-icons/ri"
export { SiAnydesk as AnyDesk } from "react-icons/si"
export { SiCanva as Canva } from "react-icons/si"
export { SiDbeaver as Dbeaver } from "react-icons/si"
export { SiJavascript as JavaScript } from "react-icons/si"
export { SiMicrosoftonenote as OneNote } from "react-icons/si"
export { SiObsstudio as OBSStudio } from "react-icons/si"
export { SiOpenai as ChatGPT } from "react-icons/si"
export { SiPostman as Postman } from "react-icons/si"
export { SiPowershell as Powershell } from "react-icons/si"
export { SiSpotify as Spotify } from "react-icons/si"
export { SiVirtualbox as VirtualBox } from "react-icons/si"
export { SiVisualstudiocode as VSCode } from "react-icons/si"
export { VscGithub as GithubDesktop } from "react-icons/vsc"
export { VscJson as Json } from "react-icons/vsc"
