"use client"

/**
 * @description all application icons
 * @type {IconType}
 * @returns {React.JSX.Element}
 */
export { BiLogoTypescript as TypeScript } from "react-icons/bi"
export { CgRemote as RemoteDesktop } from "react-icons/cg"
export { FaArrowTurnUp as Up } from "react-icons/fa6"
export { FaAws as Aws } from "react-icons/fa6"
export { FaBootstrap as Bootstrap } from "react-icons/fa6"
export { FaGitAlt as Git } from "react-icons/fa"
export { FaGulp as Gulp } from "react-icons/fa6"
export { FaNodeJs as Node } from "react-icons/fa"
export { FaPython as Python } from "react-icons/fa6"
export { FaReact as React } from "react-icons/fa"
export { FaSass as Scss } from "react-icons/fa6"
export { GrMysql as MySQL } from "react-icons/gr"
export { IoEye as Eye } from "react-icons/io5"
export { IoIosArrowDown as Arrow } from "react-icons/io"
export { IoLogoCss3 as Css } from "react-icons/io"
export { IoLogoFirebase as Firebase } from "react-icons/io5"
export { IoLogoGithub as Github } from "react-icons/io5"
export { IoLogoHtml5 as Html } from "react-icons/io5"
export { IoLogoMarkdown as Markdown } from "react-icons/io5"
export { IoMoon as Moon } from "react-icons/io5"
export { IoSunnySharp as Sun } from "react-icons/io5"
export { RiNextjsFill as Next } from "react-icons/ri"
export { RiTailwindCssFill as Tailwind } from "react-icons/ri"
export { SiAnydesk as AnyDesk } from "react-icons/si"
export { SiAxios as Axios } from "react-icons/si"
export { SiBabel as Babel } from "react-icons/si"
export { SiCanva as Canva } from "react-icons/si"
export { SiDbeaver as Dbeaver } from "react-icons/si"
export { SiDelphi as Delphi } from "react-icons/si"
export { SiEslint as ESLint } from "react-icons/si"
export { SiExpress as Express } from "react-icons/si"
export { SiFlask as Flask } from "react-icons/si"
export { SiGnubash as Bash } from "react-icons/si"
export { SiGrafana as Grafana } from "react-icons/si"
export { SiJavascript as JavaScript } from "react-icons/si"
export { SiJquery as Jquery } from "react-icons/si"
export { SiMariadb as MariaDB } from "react-icons/si"
export { SiMicrosoftonenote as OneNote } from "react-icons/si"
export { SiMicrosoftsqlserver as SQLServer } from "react-icons/si"
export { SiMongodb as MongoDB } from "react-icons/si"
export { SiNodemon as Nodemon } from "react-icons/si"
export { SiObsstudio as OBSStudio } from "react-icons/si"
export { SiOpenai as ChatGPT } from "react-icons/si"
export { SiOracle as Oracle } from "react-icons/si"
export { SiPandas as Pandas } from "react-icons/si"
export { SiPlotly as Plotly } from "react-icons/si"
export { SiPostman as Postman } from "react-icons/si"
export { SiPowershell as Powershell } from "react-icons/si"
export { SiPowershell as Shell } from "react-icons/si"
export { SiSpotify as Spotify } from "react-icons/si"
export { SiSqlalchemy as SQLAlchemy } from "react-icons/si"
export { SiVercel as Vercel } from "react-icons/si"
export { SiVirtualbox as VirtualBox } from "react-icons/si"
export { SiVisualstudiocode as VSCode } from "react-icons/si"
export { SiVite as Vite } from "react-icons/si"
export { SiWebpack as Webpack } from "react-icons/si"
export { VscAzure as Azure } from "react-icons/vsc"
export { VscGithub as GithubDesktop } from "react-icons/vsc"
export { VscJson as Json } from "react-icons/vsc"
