/**
 * @description API de ícones responsável por exportar todos os ícones presentes no projeto
 * @type IconType
 */

export { BiLogoJavascript as JavaScript } from "react-icons/bi"
export { BiLogoTypescript as TypeScript } from "react-icons/bi"
export { BiLogoVuejs as VueJS } from "react-icons/bi"
export { CgClose as Close } from "react-icons/cg"
export { CgSearch as Search } from "react-icons/cg"
export { FaGitAlt as Git } from "react-icons/fa"
export { FaGulp as Gulp } from "react-icons/fa6"
export { FaHtml5 as Html } from "react-icons/fa6"
export { FaNodeJs as NodeJS } from "react-icons/fa6"
export { FaPython as Python } from "react-icons/fa"
export { FaReact as React } from "react-icons/fa6"
export { FaSass as Scss } from "react-icons/fa6"
export { FiLink as Url } from "react-icons/fi"
export { GrMysql as MySQL } from "react-icons/gr"
export { HiOutlineMenu as NavbarMenu } from "react-icons/hi"
export { IoCodeSharp as CodeSymbol } from "react-icons/io5"
export { IoLogoCss3 as Css } from "react-icons/io"
export { IoLogoGithub as GitHub } from "react-icons/io5"
export { IoLogoLinkedin as LinkedIn } from "react-icons/io5"
export { IoMailUnread as Mail } from "react-icons/io5"
export { MdLanguage as Language } from "react-icons/md"
export { MdOutlineDarkMode as DarkMode } from "react-icons/md"
export { MdOutlineLightMode as LightMode } from "react-icons/md"
export { RiNextjsFill as NextJS } from "react-icons/ri"
export { SiJquery as Jquery } from "react-icons/si"
export { SiMicrosoftsqlserver as SQLServer } from "react-icons/si"
export { SiMongodb as MongoDB } from "react-icons/si"
export { SiOracle as Oracle } from "react-icons/si"
export { SiQuicklook as Preview } from "react-icons/si"
export { SiTailwindcss as Tailwind } from "react-icons/si"
